name: ChromeDriver
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Chrome
      uses: nanasess/setup-chromedriver@v1
      with:
        chrome-version: 'latest'  # Or specify a particular version
        chromedriver-version: 'latest'  # Or specify a particular version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python main.py
